block: maple-iosched: Disable 'compare-distinct-pointer-types' warnings
For a moment I thought I had introduced some less than stellar code
during the drm_notifier conversion. Turns the scheduler has been
poorly coded all along (according to Clang). I should probably take
this as a sign, but we can let it slide until I get a chance to go
back and rewrite the offending conditionals. For the time being,
these warnings are reletively benign and can be ignored without any
cataclysmic repercussions. Maple has made it this far as is.

This silences the following compiler warnings:

../block/maple-iosched.c:69:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
                if (time_before(next->fifo_time, rq->fifo_time)) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:105:26: note: expanded from macro 'time_before'
                                ^~~~~~~~~~~~~~~
../include/linux/jiffies.h:102:3: note: expanded from macro 'time_after'
        (typecheck(unsigned long, a) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:69:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (next->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
                if (time_before(next->fifo_time, rq->fifo_time)) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:105:26: note: expanded from macro 'time_before'
                                ^~~~~~~~~~~~~~~
../include/linux/jiffies.h:103:3: note: expanded from macro 'time_after'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:115:6: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
        if (time_after_eq(jiffies, rq->fifo_time))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:109:3: note: expanded from macro 'time_after_eq'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:138:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_sync_read->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_read->fifo_time, rq_async_read->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:102:3: note: expanded from macro 'time_after'
        (typecheck(unsigned long, a) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:138:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_async_read->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_read->fifo_time, rq_async_read->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:103:3: note: expanded from macro 'time_after'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:147:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_sync_write->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_write->fifo_time, rq_async_write->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:102:3: note: expanded from macro 'time_after'
        (typecheck(unsigned long, a) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~
../block/maple-iosched.c:147:7: error: comparison of distinct pointer types
('unsigned long *' and 'typeof (rq_async_write->fifo_time) *' (aka 'unsigned long long *')) [-Werror,-Wcompare-distinct-pointer-types]
                if (time_after(rq_sync_write->fifo_time, rq_async_write->fifo_time))
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/jiffies.h:103:3: note: expanded from macro 'time_after'
         typecheck(unsigned long, b) && \
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/typecheck.h:11:18: note: expanded from macro 'typecheck'
        (void)(&__dummy == &__dummy2); \
               ~~~~~~~~ ^  ~~~~~~~~~

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: DennySPB <dennyspb@gmail.com>