kernel/printk: Properly guard unused-variable
Subsequent to b6ca0f4 ("kernel/printk: Convert to hotplug state machine")

This silences the following compiler warning:

../kernel/printk/printk.c:2850:6: error: unused variable 'ret'
[-Werror,-Wunused-variable]
        int ret;
            ^
1 error generated.

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: DennySPB <dennyspb@gmail.com>